language: python
sudo: required
dist: xenial
stages:
- test
- name: deploy
  if: tag IS present
python:
- '2.7'
- '3.6'
- '3.7'
install: pip install tox coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success: coveralls
jobs:
  include:
  - stage: deploy
    python: '3.6'
    install: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      on:
        tags: true
      distributions: sdist bdist_wheel
      user: gregoil
      password:
        secure: rTyJouQ7BLOKO5KZDkQFFxepf1rUotheu3TOVwZVaHB4ZYaNbFWy1brh789+wtoGEMaacyHfzfmzM7/kwkBuMpRV4RJ5rt3GMYmCsa4OJrVuBGyRSUPgU/X3o9DSCIv6RxN3YLYLEKHrfOYVpqu9lsyt6Qi6YxTmJvqMzboTrpxbkqvnL1oTGkwBSvckSODV77OOLwrslb842x0+cSH+lvYqes6hJ8++FGN98wp3IjY12m9iZxWbGR34MEGBS7RT73853U/P80f4Zx386sjYQA4Hr61mXW4Wb5Y1l7YDZfK0QoLxc0PnC0hyVzCj9Yz2GuKl6B2iCdIMzegmDtQ7Mruhl9u0XKPYpMeXZa3EU1VZ2yGsjkU2bk/f0CPx6T8G4HqORgnveJ59SKMPzSiH6vbq6aq3Sl/0XeUb2MoxWJ/Tim8RbhXGZ0ze8evP4iA49rgrpLzmpA5wflR8fg9B2Xl1QcKgrDDdovSTWgWlYJNPJeMkVYkhDCxb0dnet9587D5+Tb9XHg+cDkgKJT9/GoeJq4FUNF8CLdQHXewv5r5ucIF8tJuadOH1x564mfPFePiRtTbJOduNEEyJJwoUNhxx4kdOPuoA5pSYA07xntLXeS2Qs+QH5Vc42QQyFJK1xCmcbfeWs2DT7iQzAXjd8Xl56WmVnoyEBTlmKcueR8Y=
